classmates=['a','b','c']
print(classmates)
print(len(classmates))
print(classmates[1])
print(classmates[-1])
print(classmates[-3])
classmates.append('d')
print(classmates)
classmates.insert(1,'aa')
print(classmates)
classmates.pop()#删除list 末尾元素
print(classmates)
classmates.pop(1)#删除指定位置的元素
print(classmates)
classmates[1]='BBB'#替换指定位置元素
print(classmates)
L=['A',123,True]#list元素类型可以不同
print(L)
s=['AA','BBB',L]
print(s)
print(len(s))
print(s[2][1])
t=('a','b','c',s)#tuple的每个元素指向不变
print(t)
t[3][0]='A'
t[3][1]='BB'
print(t)

'''
多行注释
'''
#单行注释